package com.alto.id.bifast.simulator.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BankAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankAllPropertiesEquals(Bank expected, Bank actual) {
        assertBankAutoGeneratedPropertiesEquals(expected, actual);
        assertBankAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankAllUpdatablePropertiesEquals(Bank expected, Bank actual) {
        assertBankUpdatableFieldsEquals(expected, actual);
        assertBankUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankAutoGeneratedPropertiesEquals(Bank expected, Bank actual) {
        assertThat(expected)
            .as("Verify Bank auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankUpdatableFieldsEquals(Bank expected, Bank actual) {
        assertThat(expected)
            .as("Verify Bank relevant properties")
            .satisfies(e -> assertThat(e.getBicCode()).as("check bicCode").isEqualTo(actual.getBicCode()))
            .satisfies(e -> assertThat(e.getBankName()).as("check bankName").isEqualTo(actual.getBankName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankUpdatableRelationshipsEquals(Bank expected, Bank actual) {
        // empty method
    }
}
